language: node_js
node_js:
  - "6"
  - "8"
  - "10"
install: npm install

jobs:
    include:
    - stage: linting
      node_js: "10"
      script: npm run lint

    - stage: tests
      script: npm run test
      node_js: "6"
    - node_js: "8"

    - stage: coverage
      script: npm run ci-test
      node_js: "10"

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtlZ2FuJTNBbWF0cml4Lm9yZy8lMjFTdWR2aU9KbGltRHZyR2RGQ1klM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: change
        on_start: never
